# Generated by Django 4.1.7 on 2024-09-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
