# Generated by Django 4.1.7 on 2024-09-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_product_category_delete_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='matric_number',
            field=models.IntegerField(null=True),
        ),
    ]
