# Generated by Django 4.1.7 on 2024-09-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_matric_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
