# Generated by Django 4.1.7 on 2024-09-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='matric_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
