# Generated by Django 4.1.7 on 2024-09-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_profile_matric_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pics',
            field=models.ImageField(default='', null=True, upload_to='pics'),
        ),
    ]
