# Generated by Django 4.1.7 on 2024-09-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_profile_username_profile_profile_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
