# Generated by Django 4.1.7 on 2024-09-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_profile_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='residential_address',
            new_name='department',
        ),
    ]
