# Generated by Django 4.1.7 on 2024-09-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_rename_residential_address_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
