# Generated by Django 4.1.7 on 2024-09-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_profile_profile_pics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pics',
        ),
    ]
